baseURL = 'https://christopher-eller.de/'
languageCode = 'de-DE'
title = 'Christopher Eller'

[outputs]
home = ["HTML", "RSS", "OGIMAGE"]
section = ["HTML", "OGIMAGE"]
page = ["HTML", "OGIMAGE"]

# Changes rss-feed to feed.xml
[outputFormats.RSS]
baseName = "feed"

# Custom output format for OpenGraph images
[outputFormats.OGIMAGE]
mediaType = "image/svg+xml"
baseName = "og-image"
isPlainText = true
notAlternative = true
permalinkable = false

# Number of items per page in lists
paginate = 10
paginatePath = "page"

[params]
  description = "Personal website of Christopher Eller - Sharing texts, links, and photos"
  favicon = true
  site_manifest = "/site.webmanifest"
  
  # Twitter handle (without the @)
  [params.social]
    twitter = "chriopter"

[markup.goldmark.renderhooks.image]
  enable = true
  multilingualOnly = false

[markup.goldmark.renderhooks.link]
  enable = true
  multilingualOnly = false
