baseURL = 'https://christopher-eller.de/'
languageCode = 'de-DE'
title = 'Christopher Eller'
theme = 'modulunar'

[outputs]
home = ["HTML", "RSS"]
section = ["HTML"]
page = ["HTML"]

# Changes rss-feed to feed.xml
[outputFormats.RSS]
baseName = "feed"

# Number of items per page in lists
paginate = 10
paginatePath = "page"

[params]
  favicon = true
  site_manifest = "/site.webmanifest"
  enablePhotosModule = true

[markup.goldmark.renderhooks.image]
  enable = true
  multilingualOnly = false

[markup.goldmark.renderhooks.link]
  enable = true
  multilingualOnly = false

[markup.goldmark.renderer]
  unsafe = true
