baseURL = 'https://christopher-eller.de/'
languageCode = 'de-DE'
title = 'Christopher Eller'

# Enable pagination
[pagination]
  pagerSize = 10
  path = "page"

[params]
  favicon = true
  site_manifest = "/site.webmanifest"