baseURL = 'https://christopher-eller.de/'
languageCode = 'de-DE'
title = 'Christopher Eller'

# Enable pagination
[pagination]
  pagerSize = 10
  path = "page"

[params]
  favicon = true
  site_manifest = "/site.webmanifest"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Allow HTML in markdown files
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
