name: Auto-merge PRs
on:
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [auto-merge-pr]

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""  # No labels required
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"

  auto-merge-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'repository_dispatch' && github.event.client_payload.event_type == 'auto-merge-pr'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""  # No labels required
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          PULL_REQUEST: "${{ github.event.client_payload.pr_number }}"
